### ISSUE TITLE
Rotate Image

### ISSUE THREAD

**Issue by mamanico1** [CrackerakiUA/ui-cropper#79] opened 2018-09-26 09:12 UTC
Hey, is anyone add image rotation option to this? if so, can he please share?
@CrackerakiUA  Are u planning to add this option?

**Comment by CrackerakiUA** [comment] 2018-09-26 11:19
Hey, i was planning that, but currently it's not under to do list.

**Comment by rickerd** [comment] 2019-05-27 12:22
Not on the roadmap? Maybe closing the issue is better?

**Closed** 2019-05-27 16:43 UTC
