### ISSUE TITLE
Cropper not rendered into ui bootstrap modal

### ISSUE THREAD

**Issue by swordman1205** [CrackerakiUA/ui-cropper#57] opened 2017-10-03 09:58 UTC
Hi, I have an issue in rendering cropper into ui bootstrap modal. It works well for smaller images, but not for bigger ones. This is weird issue since it's worked well before. Not sure since when it's started not working. Let me share some of codebase.

```
angular.element(document.querySelector('#cover-photo-trigger')).on('change', function(evt) {
          var file = evt.currentTarget.files[0];
          var reader = new FileReader();
          reader.onload = function () {
            var image = new Image();
            image.onload = function() {
                    var modalInstance = $modal.open({
                      templateUrl: 'views.promoter.modals.cover-upload',
                      controller: function($scope, $modalInstance, data) {
                        $scope.image = data.image;
                        $scope.croppedImg = '';
                        $scope.width = data.width;
                        $scope.height = data.height;

                        $scope.cancel = function() {
                            $modalInstance.dismiss('cancel');
                        }

                        $scope.cropImage = function() {
                            $modalInstance.close($scope.croppedImg);
                        }
                      },
                      size: 'lg',
                      windowClass: 'cover-popup',
                      resolve: {
                        data: function () {
                          return {
                            image: reader.result,
                            width: image.width,
                            height: image.height
                          };
                        }
                      }
                    });

                    modalInstance.result.then(function (croppedImg) {
                      ...
                    }, function () {
                      console.log('modal dismissed');
                    });
            }
            image.src = reader.result;            
          };
          if (file) {
            reader.readAsDataURL(file);
            angular.element(document.querySelector('#cover-photo-trigger'))[0].value = ''; 
          }
        });
```

Here is modal template:

```
<div class="modal-header">
  <h2 class="modal-title">Crop Image</h2>
</div>
<div class="modal-body">
  <div style="width: {{ width }}px; height: {{ height }}px; margin: 0 auto;">
    <ui-cropper image="image" area-type="rectangle" result-image="croppedImg"></ui-cropper>
  </div>
</div>
<div class="modal-footer">
  <button class="btn btn-md btn-gray" ng-click="cancel()">
    Cancel
  </button>
  <button class="btn btn-md btn-orange" ng-click="cropImage()">
    Ok
  </button>
</div>

```

Looking forward to your reply.
Thanks!

**Comment by CrackerakiUA** [comment] 2017-10-03 10:09
Please explain, what exactly is happening with big images.

**Comment by RHinderiks** [comment] 2017-10-03 14:39
Which version of angular js are you using ?  We are running on 1.2.* and we can load the directive, but while using the example code provided it just shows a grey area after loading.

**Comment by NataliaMekh** [comment] 2017-10-09 16:47
I am using ngDialog and have the same problem: When upload big images I can't change cropped area and cant move it. Also on laptops it doesn't work even with smaller images. Please, help to solve it. Thanks!

**Comment by CrackerakiUA** [comment] 2017-10-09 20:54
to help you, i need somehow reproduce that. in my case i don't have such issue. In different case, you have to debug it, and find the issue. We will love to have PR if you fix it.

**Comment by RHinderiks** [comment] 2017-10-10 08:08
The issue we seem to have happens on a "normal" page as well not only a ui bootstrap modal

**Comment by rickerd** [comment] 2017-10-10 08:17
@NataliaMekh what i an big image?
I made a website what can crop a very big image (5000x5000). I never had any problems with the library.

We're the "owners" of the project but not the owners of the product. It's an open sourced product and everything we needed in the cropper is what we've made. Some things were already made by the original maker of the plugin.
We also don't have an answer for every problem and appreciate every piece of code that is made by any developer.

**Comment by CrackerakiUA** [comment] 2017-10-10 08:29
@RHinderiks or @swordman1205 please provide code setup with images you use to reproduce the issue.

**Comment by CrackerakiUA** [comment] 2018-02-08 20:27
Closing the issue as we can't reproduce it.

**Closed by CrackerakiUA** 2018-02-08 20:27 UTC

**Comment by pedrodavidept** [comment] 2020-09-21 10:09
> I am using ngDialog and have the same problem: When upload big images I can't change cropped area and cant move it. Also on laptops it doesn't work even with smaller images. Please, help to solve it. Thanks!

Did you fix that? I'm having the same problem using ngDialog. It works when first open of dialog, but in the second time that cropped are can't move!
