### ISSUE TITLE
MegaPixImage fails for strict-di

### ISSUE THREAD

**Issue by vjoao** [CrackerakiUA/ui-cropper#14] opened 2016-12-01 17:48 UTC
I'm using ES6 with webpack and strict di.

The error I'm getting after importing 'uiCropper' is: 
```
Error: [$injector:strictdi] MegaPixImage is not using explicit annotation and cannot be invoked in strict mode
```

even though MegaPixImage has nothing to do with angular.
Any thoughts?

**Comment by CrackerakiUA** [comment] 2016-12-01 18:04
Never seen this before.

**Comment by vjoao** [comment] 2016-12-07 11:17
Found the issue.
Your module definition is actually exporting the MegaPixImage function for some reason.

I was doing:

`import uiCropper from 'ui-cropper';`

```
angular.module('app', [
...
uiCropper
]
```

but uiCropper in this context is not `uiCropper`, it is actually `MegaPixImage`.
I guess you have to review your module definitions.

**Comment by xitasoappdev** [comment] 2017-03-15 07:46
same error for me. unfortunately not working with Angular 1.6

**Comment by CrackerakiUA** [comment] 2017-03-15 08:37
Probably we use this module differently, can you provide an solution for this problem?

**Comment by rickerd** [comment] 2017-06-12 09:48
No suggestions are made, closing for now.

**Closed by rickerd** 2017-06-12 09:48 UTC

**Comment by RubcovSA** [comment] 2018-03-21 03:42
Does anybody solve it?

**Comment by gamegenius86** [comment] 2019-10-29 19:54
This is caused by final function (iife) in the compiled unminified version of the code to include `module.exports = MegaPixImage`.  To solve this the compiled version must do the module export `module.exports = 'uiCropper';` last.

Solution for the time being would be to just require above your `angular.module()` definition and manually put `uiCropper` as a dependancy.

**Comment by CrackerakiUA** [comment] 2019-10-29 20:24
feel free to make PR
